import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Vanessa Chans',
  description: 'Vanessa Chans\' portofolio, generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://v-chns.github.io/portofolio/favicon.ico" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
